; @expanto hidden: 1

; Vanliga svenska felstavningar -> rättstavning (autocorrect).
; Källor: Wikipedia:AutoWikiBrowser/Typos (sv) + Lista över vanliga språkfel (CC BY-SA 4.0).
; 834 poster. Sammanslaget från autocorrect_sv, svenska_felstavningar, svenska_felstavningar_2.

; ---- Inuti ord  :?*:  (789 st) ----

:?*:abbonemang::abonnemang ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:abbonent::abonnent ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:abbonnemang::abonnemang ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:abbonnent::abonnent ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:abedissa::abbedissa ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:abonemang::abonnemang ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:abonent::abonnent ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:aborre::abborre ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:abrubt::abrupt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:absorbtion::absorption ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:adelsskap::adelskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:adminstrativ::administrativ ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:advancera::avancera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:advokado::avokado ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:affish::affisch ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Afganistan::Afghanistan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:aggresiv::aggressiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:agressiv::aggressiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:akseptera::acceptera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:aliera::alliera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:alldenes::alldeles ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:alldrig::aldrig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:allför::alltför ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:allmer::alltmer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:allmäna::allmänna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:allmänn::allmän ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:allmännhet::allmänhet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:allmännt::allmänt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:almenacka::almanacka ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:altså::alltså ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:alvarlig::allvarlig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:amalgan::amalgam ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ambasad::ambassad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ambasadör::ambassadör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:amiralskepp::amiralsskepp ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anant::annat ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:andefådd::andfådd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:andledning::anledning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:andvänd::använd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anektera::annektera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anfallspel::anfallsspel ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anfals::anfalls ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anglosaxer::anglosaxare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anglosaxerna::anglosaxarna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anlägning::anläggning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:annordna::anordna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:annulera::annullera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anspråklös::anspråkslös ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:anullera::annullera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:använding::användning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:arangera::arrangera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:arbetarebost::arbetarbost ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:arbetssam::arbetsam ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:arbetsätt::arbetssätt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:arkelog::arkeolog ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:armensk::armenisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:artelleri::artilleri ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:artifakt::artefakt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:artificell::artificiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:artiklen::artikeln ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:arvsskifte::arvskifte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:asbets::asbest ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:asseptera::acceptera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:assymetri::asymmetri ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:astonom::astronom ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:asymetri::asymmetri ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:atelje::ateljé ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:attograf::autograf ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:australienare::australiensare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:avgorde::avgjorde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:avsaknand::avsaknad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Azerbadjan::Azerbajdzjan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Azerbadzjan::Azerbajdzjan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:baggage::bagage ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bakrund::bakgrund ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ballet::balett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ballett::balett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bassist::basist ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:basäng::bassäng ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:beaktning::beaktande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bebolig::beboelig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bedömm::bedöm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:befodra::befordra ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:befolkningstatistik::befolkningsstatistik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:begågna::begångna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:behållt::behållit ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bequerel::becquerel ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bequerell::becquerel ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bergrund::berggrund ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:beronde::beroende ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:beskjöt::besköt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:beslagstog::beslagtog ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:betår::består ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:biblen::bibeln ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bibliotikarie::bibliotekarie ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:biblografi::bibliografi ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:biblotekarie::bibliotekarie ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:biblotikarie::bibliotekarie ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bildadet::bildandet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Bipsgården::Bispgården ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:biskopdöme::biskopsdöme ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:biskopsäte::biskopssäte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:blanding::blandning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:blixlås::blixtlås ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:blomorna::blommorna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bohusländsk::bohuslänsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bombadera::bombardera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bortag::borttag ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:boskapskötsel::boskapsskötsel ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Brazilien::Brasilien ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:braziliensisk::brasiliansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:brevid::bredvid ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:britisk::brittisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:brottsmål::brottmål ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bruksamhälle::brukssamhälle ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:brytit::brutit ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:brödrarskap::brödraskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bröllopp::bröllop ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:brölopp::bröllop ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:busshållsplats::busshållplats ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:busshålltsplats::busshållplats ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:bygnad::byggnad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:böjra::börja ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Ceasar::Caesar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:cermoni::ceremoni ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:chefsredaktör::chefredaktör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:chocklad::choklad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ciggarett::cigarett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ciggarrett::cigarett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:civilia::civila ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:colombisk::colombiansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Dannmark::Danmark ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:decenium::decennium ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:definera::definiera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:deputerandekammare::deputeradekammare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:dimention::dimension ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:discografi::diskografi ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:disel::diesel ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:disktrikt::distrikt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:diskusion::diskussion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:diskution::diskussion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:disskusion::diskussion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:disskussion::diskussion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:disskution::diskussion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:distansiera::distansera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:dommar::domar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:drukna::drunkna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:dublett::dubblett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:dylig::dylik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:dyligt::dylikt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:dynastien::dynastin ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:däför::därför ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:dödstraff::dödsstraff ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:efektiv::effektiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:efterträde::efterträdde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:egenligen::egentligen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:eljusspår::elljusspår ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:elvte::elfte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:entren::entrén ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:erfodras::erfordras ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:erkännd::erkänd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:erkännt::erkänt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:etablisemang::etablissemang ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:etioper::etiopier ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ettikett::etikett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:euroasiatisk::eurasiatisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Euroasien::Eurasien ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:europisk::europeisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:exeptionell::exceptionell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:existensialism::existentialism ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:existensiell::existentiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:exlusiv::exklusiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:experement::experiment ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:explotion::explosion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:exprement::experiment ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:expriment::experiment ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:extren::extern ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fachism::fascism ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fachist::fascist ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:facism::fascism ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:facist::fascist ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:facsism::fascism ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:facsist::fascist ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fakultetet::fakulteten ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:faschism::fascism ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:faschist::fascist ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:femenism::feminism ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:femenist::feminist ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fetme::femte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fiendeskap::fiendskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Filipinerna::Filippinerna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:filipinsk::filippinsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Fillipinerna::Filippinerna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fillipinsk::filippinsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Fillippinerna::Filippinerna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:filsof::filosof ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:finlandsvensk::finlandssvensk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:finlänsk::finländsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fiskebestånd::fiskbestånd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fiskelägret::fiskeläget ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fjärilssim::fjärilsim ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fleral::flertal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fluorecera::fluorescera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fluoresera::fluorescera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fluoricera::fluorescera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fluoriscera::fluorescera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fluorisera::fluorescera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:flyckten::flykten ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:flygit::flugit ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:foaje::foajé ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:formattera::formatera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:formelt::formellt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:forminne::fornminne ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fornordisk::fornnordisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:forsatte::fortsatte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:forsätta::fortsätta ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:forsätter::fortsätter ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fotbollspelare::fotbollsspelare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:frammåt::framåt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fridrott::friidrott ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:frisörsalong::frisersalong ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:frivilig::frivillig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:främlig::främling ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fyrårig::fyraårig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:färggrannt::färggrant ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:färgrann::färggrann ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:färjelägre::färjeläge ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:färjförbindelse::färjeförbindelse ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fångeskap::fångenskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:följdaktligen::följaktligen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förbild::förebild ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:föredel::fördel ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:föredömme::föredöme ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förekomer::förekommer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förens::förrän ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:företeckning::förteckning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:företrädelsevis::företrädesvis ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förkommande::förekommande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förkommer::förekommer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förkomst::förekomst ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förläsning::föreläsning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förmodlingen::förmodligen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förmål::föremål ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förns::förrän ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förnärvarande::för närvarande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förren::förrän ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förrens::förrän ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förräns::förrän ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förschyld::förkyld ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förskyld::förkyld ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förspråka::förespråka ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förstörning::förstöring ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:försöj::försörj ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förtyck::förtryck ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:förutspråka::förespråka ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:föråd::förråd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:fösta::första ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:gammla::gamla ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:garnision::garnison ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:gemensammt::gemensamt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:genetiv::genitiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:genral::general ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:genrena::genrerna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:germanisk::germansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:giftemål::giftermål ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:giltlig::giltig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:gittar::gitarr ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:grundandes::grundades ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:grupen::gruppen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:guvenör::guvernör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:guvernment::guvernement ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:gynsam::gynnsam ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:gågna::gångna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hadde::hade ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hafft::haft ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:halvägs::halvvägs ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:handbollspelare::handbollsspelare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:handlig::handling ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hebréisk::hebreisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hembygs::hembygds ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hemmarena::hemmaarena ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hertigdömme::hertigdöme ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hetro::hetero ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hitills::hittills ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hittils::hittills ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hollänsk::holländsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:honnom::honom ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:horizontell::horisontell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hurvida::huruvida ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hyffsad::hyfsad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hyffsat::hyfsat ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hämntdatum::hämtdatum ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:härstammning::härstamning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:härör::härrör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hållde::höll ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hållt::hållit ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hårddra::hårdra ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hörrör::härrör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:hövidsman::hövitsman ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:iakta::iaktta ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:iaktagelse::iakttagelse ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:iallafall::i alla fall ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:identifera::identifiera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:idéen::idén ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:igentligen::egentligen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:illustera::illustrera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:imellan::emellan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:immitera::imitera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inblanding::inblandning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:indentifiera::identifiera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:indentifikation::identifikation ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:indoeuropisk::indoeuropeisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:indvid::individ ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:infantri::infanteri ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inflytade::inflytande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inflytesrik::inflytelserik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:infomation::information ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:infromation::information ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inhängna::inhägna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:iniativ::initiativ ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:initativ::initiativ ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:initera::initiera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inkorperera::inkorporera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inledningvis::inledningsvis ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:innifrån::inifrån ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:innom::inom ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:innomhus::inomhus ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:innuti::inuti ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inofficiel::inofficiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:inoficiell::inofficiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:insektlarv::insektslarv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:insperation::inspiration ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:institition::institution ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:instution::institution ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:instutition::institution ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:instutution::institution ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:interjuv::intervju ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:intervjuv::intervju ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:intiativ::initiativ ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:intilligande::intilliggande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:intoducera::introducera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:invation::invasion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:iordning::i ordning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:iordningsställ::iordningställ ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:istort::i stort ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:isåfall::i så fall ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jamaikan::jamaican ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jamaikansk::jamaicansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jannuari::januari ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jorbruk::jordbruk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jungru::jungfru ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:justite::justitie ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jämnför::jämför ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jämnlik::jämlik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jämnställ::jämställ ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:jämnvikt::jämvikt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:järnvägstation::järnvägsstation ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:järväg::järnväg ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Kaanan::Kanaan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kakafoni::kakofoni ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kaligrafi::kalligrafi ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kallde::kallade ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kamare::kammare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kammrar::kamrar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kapasitet::kapacitet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kariär::karriär ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kariärr::karriär ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:karnival::karneval ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:karrikatyr::karikatyr ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Kasakstan::Kazakstan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kasett::kassett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kasset::kassett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kassetband::kassettband ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kategorien::kategorin ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Kirgisistan::Kirgizistan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kirug::kirurg ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:knytpunkt::knutpunkt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kolaps::kollaps ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kolidera::kollidera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kollosal::kolossal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kollossal::kolossal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komerciell::kommersiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komers::kommers ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komersiell::kommersiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komisarie::kommissarie ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komissarie::kommissarie ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komission::kommission ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komitté::kommitté ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kommerciell::kommersiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kommisarie::kommissarie ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kommision::kommission ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kommité::kommitté ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kompabilitet::kompatibilitet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kompletera::komplettera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komposera::komponera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:komun::kommun ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:koncerter::konserter ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:koncistens::konsistens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konjuktiv::konjunktiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konkurans::konkurrens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konkurens::konkurrens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konkurent::konkurrent ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konkurera::konkurrera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konkurrans::konkurrens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konsoll::konsol ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konsruera::konstruera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstmuséer::konstmuseer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstmuséet::konstmuseet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstnärsskap::konstnärskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstrast::kontrast ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstrera::konstruera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstruea::konstruera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstrura::konstruera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konstuera::konstruera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konsumption::konsumtion ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kontigent::kontingent ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kontruera::konstruera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konvalecens::konvalescens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konvalecent::konvalescent ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konvalesens::konvalescens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:konvalesent::konvalescent ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kostruera::konstruera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:krach::krasch ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:krash::krasch ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:krigsföring::krigföring ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:krigslut::krigsslut ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kristendommen::kristendomen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kriterie::kriterium ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kundskap::kunskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kungadömme::kungadöme ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kunlig::kunglig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kunnde::kunde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kvartfinal::kvartsfinal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kvinlig::kvinnlig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kyrkrum::kyrkorum ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kännt::känt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:kålla::kolla ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:landegendom::lantegendom ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:landhövding::landshövding ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:landsgräns::landgräns ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:landslagspelar::landslagsspelar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:lanskap::landskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:latisnk::latinsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:leauge::league ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ledarmot::ledamot ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:leveratör::leverantör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:levnadsätt::levnadssätt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:likande::liknande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:livstil::livsstil ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:lutersk::luthersk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:luxemburgisk::luxemburgsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:länghopp::längdhopp ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:länstyrelse::länsstyrelse ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:låneord::lånord ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:majonäs::majonnäs ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:makedoner::makedonier ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:malajsisk::malajisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:marchera::marschera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:marsalk::marskalk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:matrial::material ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medans::medan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medecin::medicin ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medela::meddela ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medelmåttlig::medelmåttig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:mediaföretag::medieföretag ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:mediespelare::mediaspelare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:mediumet::mediet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medlemar::medlemmar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medlemen::medlemmen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medlemsskap::medlemskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:medlemstat::medlemsstat ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:mexicansk::mexikansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:milimeter::millimeter ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:miljad::miljard ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:millitär::militär ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:minnesten::minnessten ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Missisippi::Mississippi ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:modermål::modersmål ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:modifera::modifiera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:modifering::modifiering ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:mongolsk::mongolisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:mordern::modern ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:motstats::motsats ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:musikvideos::musikvideor ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:muséer::museer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:muséet::museet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:namet::namnet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nasalisera::nasalera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nederlänsk::nederländsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:noggrannt::noggrant ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nogrann::noggrann ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nogrannt::noggrant ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nummret::numret ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nurvarande::nuvarande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nyvarande::nuvarande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nämde::nämnde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:nämnligen::nämligen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:någongång::någon gång ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ochså::också ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:offciell::officiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:offeciel::officiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:offeciell::officiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:officell::officiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:officeraren::officeren ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:officerer::officerare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:officiel::officiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:oficiell::officiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ogiltlig::ogiltig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ojämt::ojämnt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:omdelbar::omedelbar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:omdömme::omdöme ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:omisskänlig::omisskännlig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:omständig::omständlig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:oragnist::organist ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ordagrannt::ordagrant ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ordensällskap::ordenssällskap ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:orginal::original ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:orginell::originell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ovanfrån::ovanifrån ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ovärdelig::ovärderlig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:packetera::paketera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:paraguyansk::paraguayansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:paralel::parallell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:paralell::parallell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::parallel::parallell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:parantes::parentes ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:parodisera::parodiera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:parralel::parallell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:parralell::parallell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:parrallel::parallell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:parrallell::parallell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:partion::partition ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pasera::passera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pastroat::pastorat ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pedestal::piedestal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pedistal::piedestal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:perifier::perifer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:peroner::personer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:persier::perser ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pidestal::piedestal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:piedistal::piedestal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pilgrimm::pilgrim ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pistage::pistasch ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:plattformer::plattformar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:plöstligt::plötsligt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pogramera::programmera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pogrammera::programmera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:polett::pollett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pollet::pollett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:polyneser::polynesier ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:populärisera::popularisera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:populäritet::popularitet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:portugisk::portugisisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:posetiv::positiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:poulär::populär ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:premär::premiär ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pressentera::presentera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:princessa::prinsessa ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:priviligerad::privilegierad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:priviligierad::privilegierad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:privligerad::privilegierad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:profesionell::professionell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:profesor::professor ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:proffesionell::professionell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:proffesor::professor ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:proffessionell::professionell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:proffessor::professor ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:programen::programmen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:programera::programmera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:programet::programmet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:projket::projekt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:proppeller::propeller ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:prosedur::procedur ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:provosera::provocera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:psykadelisk::psykedelisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:pubbar::pubar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:publisera::publicera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:puertorikan::puertorican ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:puertorikansk::puertoricansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:påminnd::påmind ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:raport::rapport ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:raportera::rapportera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:rebbell::rebell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:regelbunda::regelbundna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:regeringtid::regeringstid ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:regionshuvudstad::regionhuvudstad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:regisera::regissera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:regisör::regissör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:regisörr::regissör ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:religös::religiös ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:repetion::repetition ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:repetoar::repertoar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:rescension::recension ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:resension::recension ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:restrerande::resterande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:resturang::restaurang ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:resultatslös::resultatlös ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:riksdagman::riksdagsman ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:rikspelman::riksspelman ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:romerks::romersk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:rättsystem::rättssystem ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:rättsäkerhet::rättssäkerhet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:samlingalbum::samlingsalbum ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:samlingregering::samlingsregering ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sammanhängade::sammanhängande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sammarbeta::samarbeta ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sammarbete::samarbete ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sammla::samla ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sammling::samling ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sandbanker::sandbankar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sanddynor::sanddyner ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sannorlik::sannolik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sannorlikhet::sannolikhet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:satelit::satellit ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:schweitzisk::schweizisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sedemera::sedermera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sekvensiell::sekventiell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:semfinal::semifinal ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:semster::semester ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:seperat::separat ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:seperation::separation ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:seperera::separera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sevärdighet::sevärdhet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:simmning::simning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sinnesjuk::sinnessjuk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sjudne::sjunde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sjukdomm::sjukdom ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:själständig::självständig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sjärt::stjärt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skapde::skapade ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skatteskyldig::skattskyldig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skeppsättning::skeppssättning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skilld::skild ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skillsmässa::skilsmässa ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skimmlar::skimlar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skjunka::sjunka ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skjöt::sköt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skogsbeklädd::skogbeklädd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skogsbevux::skogbevux ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skogsbeväxt::skogbeväxt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skottsk::skotsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skriflig::skriftlig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skärmmytsling::skärmytsling ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:skönk::sjönk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:slutningar::sluttningar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:släktenamn::släktnamn ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:släktning::släkting ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:släppde::släppte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:släpt::släppt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:soljus::solljus ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sommras::somras ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:specialicer::specialiser ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:specialicera::specialisera ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:spännade::spännande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:spårk::språk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:stadhus::stadshus ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:stadplan::stadsplan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:stadskupp::statskupp ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:statestik::statistik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:statminister::statsminister ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:statråd::statsråd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:statsekreterare::statssekreterare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:statskick::statsskick ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:steriod::steroid ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Stocholm::Stockholm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Stockhlm::Stockholm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Stockhlom::Stockholm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Stockholem::Stockholm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Stockhom::Stockholm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Stockolm::Stockholm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Stokholm::Stockholm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Storbritanien::Storbritannien ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Storbritanninen::Storbritannien ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Storbrittanien::Storbritannien ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Storbrittannien::Storbritannien ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:storstadområde::storstadsområde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:straxt::strax ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:stämmning::stämning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:störtst::störst ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:stöst::störst ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:succesiv::successiv ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sudansk::sudanesisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:suflett::sufflett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:supportar::supportrar ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:svärdsidan::svärdssidan ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:synnerlighet::synnerhet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:särskilld::särskild ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:särskillt::särskilt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:sådeles::således ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:såkallad::så kallad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:såkallat::så kallat ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tabblett::tablett ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tadjik::tadzjik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Tallin::Tallinn ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:terass::terrass ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:terorier::teorier ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:terorin::teorin ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:teräng::terräng ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tidsmät::tidmät ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tidspunkt::tidpunkt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tillfredställa::tillfredsställa ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tillfredställelse::tillfredsställelse ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tillfredställer::tillfredsställer ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tillfredställt::tillfredsställt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tillsamans::tillsammans ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tillvägagångsätt::tillvägagångssätt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tillängna::tillägna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tilsammans::tillsammans ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tingrätt::tingsrätt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tolking::tolkning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tolvte::tolfte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:toscansk::toskansk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:traditonell::traditionell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Transylvanien::Transsylvanien ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:triller::thriller ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:triologi::trilogi ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:troligvis::troligtvis ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tuberkolos::tuberkulos ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tunneban::tunnelban ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tunnt::tunt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:turisbyrå::turistbyrå ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:tvugna::tvungna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ukrainisk::ukrainsk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ungdomm::ungdom ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ungifär::ungefär ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:universitetetet::universitetet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:unvik::undvik ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upgift::uppgift ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:uppföj::uppfölj ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:uppmot::uppemot ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:uppmärksama::uppmärksamma ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:uppskattningvis::uppskattningsvis ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upptäcksresa::upptäcktsresa ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upptäcksresande::upptäcktsresande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upptäcktresande::upptäcktsresande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:uppvärming::uppvärmning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upträda::uppträda ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upträdde::uppträdde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upträder::uppträder ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:upträtt::uppträtt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ursprunlig::ursprunglig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:utagning::uttagning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:utgorde::utgjorde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:utnämd::utnämnd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:utrusting::utrustning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:vakum::vakuum ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Vancover::Vancouver ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:varannat::vartannat ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:varitet::varietet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:vartifrån::varifrån ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:vidarebefodra::vidarebefordra ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:vikig::viktig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:vilkor::villkor ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:vinnade::vinnande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:vädersträck::väderstreck ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:väldens::världens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:välkomen::välkommen ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:välkommna::välkomna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:värdhus::värdshus ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:värdslig::världslig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:växlighet::växtlighet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:våldtäckt::våldtäkt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Warsawa::Warszawa ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:webplats::webbplats ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:websida::webbsida ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:Wikitionary::Wiktionary ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:wikpedia::Wikipedia ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:wkipedia::Wikipedia ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ytliggare::ytterligare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ytterliggare::ytterligare ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ängna::ägna ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ärfarenhet::erfarenhet ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:ättikssyra::ättiksyra ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:åklagad::åtalad ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:årskifte::årsskifte ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:årskrift::årsskrift ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:återkomande::återkommande ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:åtmindstonde::åtminstone ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:åtminstonde::åtminstone ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:åtminstonne::åtminstone ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:åtminstånde::åtminstone ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:öppenhjärtlig::öppenhjärtig ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:österikisk::österrikisk ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:överaska::överraska ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:överaskning::överraskning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:överrens::överens ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:överrenskommelse::överenskommelse ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:översvämmning::översvämning ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
:?*:övervinta::övervintra ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0

; ---- Endast helt ord  ::  (45 st) ----

::address::adress ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::allså::alltså ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::altid::alltid ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::anama::anamma ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::apell::appell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::appel::appell ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::coh::och ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::deamon::daemon ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::dömm::döm ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::efekt::effekt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::endå::ändå ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::förrut::förut ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::förråde::förrådde ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::gitar::gitarr ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::gjöt::göt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::grup::grupp ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::hellst::helst ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::hämd::hämnd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::interrim::interim ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::kännd::känd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::mne::men ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::mrn::men ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::måsta::måste ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::nämd::nämnd ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::nämt::nämnt ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::ordrar::order ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::orska::orsaka ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::oxå::också ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::provis::provins ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::rendrering::rendering ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::rivde::rev ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::schweizs::Schweiz ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::smo::som ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::spm::som ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::stog::stod ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::störe::större ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::tidsskrift::tidskrift ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::titen::titeln ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::uppnåt::uppnått ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::utav::Av ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::varr::var ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::verision::version ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::västa::västra ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::winch::vinsch ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
::ädre::äldre ; cat=autocorrect|lang=sv|comment=|tags=stavning,svenska|disabled=0|priority=0
